### ISSUE TITLE
How to add multiple markers?

### ISSUE THREAD

**Issue by anujism** [mishbahr/djangocms-gmaps#5]
I see that it is using multiple child plugin instances for Map Plugin. But when I add this plugin, I can only see option to add one location. How to add multiple locations for one Map?

**Comment by mishbahr** [comment]
By default, you can as many locations as you like. Please check your settings. See http://docs.django-ms.org/en/develop/reference/configuration.html#cms-placeholder-conf

**Comment by anujism** [comment]
Thanks for the quick reply. I am using aldryn and couldn't find this configuration file. Also, Please let me know which setting to change.

**Comment by mishbahr** [comment]
With Aldryn .. I don't think you can change settings directly (I may be completely wrong.. a lot had changed since I last used the Aldryn platform). While this plugin should work in Aldryn .. unfortunately I can't help you to debug Aldryn issues. If you can reproduce this issue.. using a normal django-cms install.. please let me know. 

Many thanks.

**Comment by anujism** [comment]
I was able to install it properly but a new problem is coming. I changed the zoom level so that all the markers get visible when the page loads but it's not happening, it always loads with zoom level 13 (even when the zoom level set to 5). Any idea why this is happening?

**Comment by mishbahr** [comment]
If there are multiple markers.. map is adjusted to "fit" markers. See https://github.com/mishbahr/djangocms-gmaps/blob/master/djangocms_gmaps/static/js/djangocms_gmaps/gmaps.js#L134
